project_name: reckon
gomod:
  proxy: true
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^readme:"
    - Merge pull request
    - Merge branch
builds:
  - id: linux-armhf
    goos: [linux]
    goarch: [arm]
    goarm: [7]
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - |
        -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
        -X main.goVersion={{.Env.GO_VERSION}} -X main.pythonVersion={{.Env.PYTHON_VERSION}}
        -X main.goreleaserVersion={{.Env.GORELEASER_VERSION}}
  - id: everything-else
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - |
        -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
        -X main.goVersion={{.Env.GO_VERSION}} -X main.pythonVersion={{.Env.PYTHON_VERSION}}
        -X main.goreleaserVersion={{.Env.GORELEASER_VERSION}}
archives:
  - builds:
      - linux-armhf
      - everything-else
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: LICENSE
      - src: README.md
      - src: model/**/*.py
      - src: model/requirements.txt
      - src: model/README.md
