// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: model/api/forecast.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProphetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   []*SamplePair `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Duration float64       `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *ProphetRequest) Reset() {
	*x = ProphetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_forecast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProphetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProphetRequest) ProtoMessage() {}

func (x *ProphetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_forecast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProphetRequest.ProtoReflect.Descriptor instead.
func (*ProphetRequest) Descriptor() ([]byte, []int) {
	return file_model_api_forecast_proto_rawDescGZIP(), []int{0}
}

func (x *ProphetRequest) GetValues() []*SamplePair {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ProphetRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type SamplePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SamplePair) Reset() {
	*x = SamplePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_forecast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SamplePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplePair) ProtoMessage() {}

func (x *SamplePair) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_forecast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplePair.ProtoReflect.Descriptor instead.
func (*SamplePair) Descriptor() ([]byte, []int) {
	return file_model_api_forecast_proto_rawDescGZIP(), []int{1}
}

func (x *SamplePair) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SamplePair) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ProphetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*Forecasted `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ProphetReply) Reset() {
	*x = ProphetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_forecast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProphetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProphetReply) ProtoMessage() {}

func (x *ProphetReply) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_forecast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProphetReply.ProtoReflect.Descriptor instead.
func (*ProphetReply) Descriptor() ([]byte, []int) {
	return file_model_api_forecast_proto_rawDescGZIP(), []int{2}
}

func (x *ProphetReply) GetValues() []*Forecasted {
	if x != nil {
		return x.Values
	}
	return nil
}

type Forecasted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp float64 `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Yhat      float64 `protobuf:"fixed64,2,opt,name=yhat,proto3" json:"yhat,omitempty"`
	YhatLower float64 `protobuf:"fixed64,3,opt,name=yhatLower,proto3" json:"yhatLower,omitempty"`
	YhatUpper float64 `protobuf:"fixed64,4,opt,name=yhatUpper,proto3" json:"yhatUpper,omitempty"`
}

func (x *Forecasted) Reset() {
	*x = Forecasted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_forecast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forecasted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecasted) ProtoMessage() {}

func (x *Forecasted) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_forecast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecasted.ProtoReflect.Descriptor instead.
func (*Forecasted) Descriptor() ([]byte, []int) {
	return file_model_api_forecast_proto_rawDescGZIP(), []int{3}
}

func (x *Forecasted) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Forecasted) GetYhat() float64 {
	if x != nil {
		return x.Yhat
	}
	return 0
}

func (x *Forecasted) GetYhatLower() float64 {
	if x != nil {
		return x.YhatLower
	}
	return 0
}

func (x *Forecasted) GetYhatUpper() float64 {
	if x != nil {
		return x.YhatUpper
	}
	return 0
}

var File_model_api_forecast_proto protoreflect.FileDescriptor

var file_model_api_forecast_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x72, 0x65,
	0x63, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22,
	0x55, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x70, 0x68, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x0a, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x50, 0x61, 0x69, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x70,
	0x68, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46,
	0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x65, 0x64, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x22, 0x7a, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x65, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x79, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x79, 0x68, 0x61,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x79, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x79, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x79, 0x68, 0x61, 0x74, 0x55, 0x70, 0x70, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x79, 0x68, 0x61, 0x74, 0x55, 0x70, 0x70, 0x65, 0x72, 0x32, 0x3d, 0x0a,
	0x08, 0x46, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x70, 0x68, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x68,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x72, 0x6f, 0x70, 0x68, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x0b, 0x5a, 0x09,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_model_api_forecast_proto_rawDescOnce sync.Once
	file_model_api_forecast_proto_rawDescData = file_model_api_forecast_proto_rawDesc
)

func file_model_api_forecast_proto_rawDescGZIP() []byte {
	file_model_api_forecast_proto_rawDescOnce.Do(func() {
		file_model_api_forecast_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_api_forecast_proto_rawDescData)
	})
	return file_model_api_forecast_proto_rawDescData
}

var file_model_api_forecast_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_api_forecast_proto_goTypes = []interface{}{
	(*ProphetRequest)(nil), // 0: api.ProphetRequest
	(*SamplePair)(nil),     // 1: api.SamplePair
	(*ProphetReply)(nil),   // 2: api.ProphetReply
	(*Forecasted)(nil),     // 3: api.Forecasted
}
var file_model_api_forecast_proto_depIdxs = []int32{
	1, // 0: api.ProphetRequest.values:type_name -> api.SamplePair
	3, // 1: api.ProphetReply.values:type_name -> api.Forecasted
	0, // 2: api.Forecast.Prophet:input_type -> api.ProphetRequest
	2, // 3: api.Forecast.Prophet:output_type -> api.ProphetReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_api_forecast_proto_init() }
func file_model_api_forecast_proto_init() {
	if File_model_api_forecast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_api_forecast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProphetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_forecast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SamplePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_forecast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProphetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_forecast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forecasted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_api_forecast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_api_forecast_proto_goTypes,
		DependencyIndexes: file_model_api_forecast_proto_depIdxs,
		MessageInfos:      file_model_api_forecast_proto_msgTypes,
	}.Build()
	File_model_api_forecast_proto = out.File
	file_model_api_forecast_proto_rawDesc = nil
	file_model_api_forecast_proto_goTypes = nil
	file_model_api_forecast_proto_depIdxs = nil
}
