# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/metrics.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61pi/metrics.proto\x12\x03\x61pi\x1a\x1bgoogle/protobuf/empty.proto\"\xc5\x01\n\x13QueryMetricsRequest\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x34\n\x06labels\x18\x02 \x03(\x0b\x32$.api.QueryMetricsRequest.LabelsEntry\x12\x11\n\tstarttime\x18\x03 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x04 \x01(\t\x12\x11\n\tchunkSize\x18\x05 \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x14QueryMetricsResponse\x12\x1c\n\x07metrics\x18\x01 \x03(\x0b\x32\x0b.api.Metric\"o\n\x06Metric\x12\'\n\x06metric\x18\x01 \x03(\x0b\x32\x17.api.Metric.MetricEntry\x12\r\n\x05value\x18\x02 \x03(\x01\x1a-\n\x0bMetricEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x13WriteMetricsRequest\x12\x1c\n\x07metrics\x18\x01 \x03(\x0b\x32\x0b.api.Metric2\x82\x01\n\x07Metrics\x12<\n\x05Query\x12\x18.api.QueryMetricsRequest\x1a\x19.api.QueryMetricsResponse\x12\x39\n\x05Write\x12\x18.api.WriteMetricsRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_QUERYMETRICSREQUEST_LABELSENTRY = _descriptor.Descriptor(
  name='LabelsEntry',
  full_name='api.QueryMetricsRequest.LabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='api.QueryMetricsRequest.LabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.QueryMetricsRequest.LabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=253,
)

_QUERYMETRICSREQUEST = _descriptor.Descriptor(
  name='QueryMetricsRequest',
  full_name='api.QueryMetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metricName', full_name='api.QueryMetricsRequest.metricName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='api.QueryMetricsRequest.labels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='starttime', full_name='api.QueryMetricsRequest.starttime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='api.QueryMetricsRequest.endTime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunkSize', full_name='api.QueryMetricsRequest.chunkSize', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUERYMETRICSREQUEST_LABELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=253,
)


_QUERYMETRICSRESPONSE = _descriptor.Descriptor(
  name='QueryMetricsResponse',
  full_name='api.QueryMetricsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='api.QueryMetricsResponse.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=307,
)


_METRIC_METRICENTRY = _descriptor.Descriptor(
  name='MetricEntry',
  full_name='api.Metric.MetricEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='api.Metric.MetricEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Metric.MetricEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=420,
)

_METRIC = _descriptor.Descriptor(
  name='Metric',
  full_name='api.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metric', full_name='api.Metric.metric', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Metric.value', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_METRIC_METRICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=420,
)


_WRITEMETRICSREQUEST = _descriptor.Descriptor(
  name='WriteMetricsRequest',
  full_name='api.WriteMetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='api.WriteMetricsRequest.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=473,
)

_QUERYMETRICSREQUEST_LABELSENTRY.containing_type = _QUERYMETRICSREQUEST
_QUERYMETRICSREQUEST.fields_by_name['labels'].message_type = _QUERYMETRICSREQUEST_LABELSENTRY
_QUERYMETRICSRESPONSE.fields_by_name['metrics'].message_type = _METRIC
_METRIC_METRICENTRY.containing_type = _METRIC
_METRIC.fields_by_name['metric'].message_type = _METRIC_METRICENTRY
_WRITEMETRICSREQUEST.fields_by_name['metrics'].message_type = _METRIC
DESCRIPTOR.message_types_by_name['QueryMetricsRequest'] = _QUERYMETRICSREQUEST
DESCRIPTOR.message_types_by_name['QueryMetricsResponse'] = _QUERYMETRICSRESPONSE
DESCRIPTOR.message_types_by_name['Metric'] = _METRIC
DESCRIPTOR.message_types_by_name['WriteMetricsRequest'] = _WRITEMETRICSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryMetricsRequest = _reflection.GeneratedProtocolMessageType('QueryMetricsRequest', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _QUERYMETRICSREQUEST_LABELSENTRY,
    '__module__' : 'api.metrics_pb2'
    # @@protoc_insertion_point(class_scope:api.QueryMetricsRequest.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : _QUERYMETRICSREQUEST,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.QueryMetricsRequest)
  })
_sym_db.RegisterMessage(QueryMetricsRequest)
_sym_db.RegisterMessage(QueryMetricsRequest.LabelsEntry)

QueryMetricsResponse = _reflection.GeneratedProtocolMessageType('QueryMetricsResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYMETRICSRESPONSE,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.QueryMetricsResponse)
  })
_sym_db.RegisterMessage(QueryMetricsResponse)

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), {

  'MetricEntry' : _reflection.GeneratedProtocolMessageType('MetricEntry', (_message.Message,), {
    'DESCRIPTOR' : _METRIC_METRICENTRY,
    '__module__' : 'api.metrics_pb2'
    # @@protoc_insertion_point(class_scope:api.Metric.MetricEntry)
    })
  ,
  'DESCRIPTOR' : _METRIC,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.Metric)
  })
_sym_db.RegisterMessage(Metric)
_sym_db.RegisterMessage(Metric.MetricEntry)

WriteMetricsRequest = _reflection.GeneratedProtocolMessageType('WriteMetricsRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEMETRICSREQUEST,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.WriteMetricsRequest)
  })
_sym_db.RegisterMessage(WriteMetricsRequest)


_QUERYMETRICSREQUEST_LABELSENTRY._options = None
_METRIC_METRICENTRY._options = None

_METRICS = _descriptor.ServiceDescriptor(
  name='Metrics',
  full_name='api.Metrics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=476,
  serialized_end=606,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='api.Metrics.Query',
    index=0,
    containing_service=None,
    input_type=_QUERYMETRICSREQUEST,
    output_type=_QUERYMETRICSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='api.Metrics.Write',
    index=1,
    containing_service=None,
    input_type=_WRITEMETRICSREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METRICS)

DESCRIPTOR.services_by_name['Metrics'] = _METRICS

# @@protoc_insertion_point(module_scope)
