# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/metrics.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61pi/metrics.proto\x12\x03\x61pi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb9\x02\n\x13QueryMetricsRequest\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x34\n\x06labels\x18\x02 \x03(\x0b\x32$.api.QueryMetricsRequest.LabelsEntry\x12)\n\x05start\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x04step\x18\x05 \x01(\x0b\x32\x19.google.protobuf.Duration\x12,\n\tchunkSize\x18\x06 \x01(\x0b\x32\x19.google.protobuf.Duration\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x14QueryMetricsResponse\x12\x1c\n\x07metrics\x18\x01 \x03(\x0b\x32\x0b.api.Metric\"\x8f\x01\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x06labels\x18\x02 \x03(\x0b\x32\x17.api.Metric.LabelsEntry\x12\x1f\n\x06values\x18\x03 \x03(\x0b\x32\x0f.api.SamplePair\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"E\n\nSamplePair\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x02 \x01(\x01\"3\n\x13WriteMetricsRequest\x12\x1c\n\x07metrics\x18\x01 \x03(\x0b\x32\x0b.api.Metric2\x82\x01\n\x07Metrics\x12<\n\x05Query\x12\x18.api.QueryMetricsRequest\x1a\x19.api.QueryMetricsResponse\x12\x39\n\x05Write\x12\x18.api.WriteMetricsRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_QUERYMETRICSREQUEST_LABELSENTRY = _descriptor.Descriptor(
  name='LabelsEntry',
  full_name='api.QueryMetricsRequest.LabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='api.QueryMetricsRequest.LabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.QueryMetricsRequest.LabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=434,
)

_QUERYMETRICSREQUEST = _descriptor.Descriptor(
  name='QueryMetricsRequest',
  full_name='api.QueryMetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metricName', full_name='api.QueryMetricsRequest.metricName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='api.QueryMetricsRequest.labels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='api.QueryMetricsRequest.start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='api.QueryMetricsRequest.end', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='api.QueryMetricsRequest.step', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunkSize', full_name='api.QueryMetricsRequest.chunkSize', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUERYMETRICSREQUEST_LABELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=434,
)


_QUERYMETRICSRESPONSE = _descriptor.Descriptor(
  name='QueryMetricsResponse',
  full_name='api.QueryMetricsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='api.QueryMetricsResponse.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=488,
)


_METRIC_LABELSENTRY = _descriptor.Descriptor(
  name='LabelsEntry',
  full_name='api.Metric.LabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='api.Metric.LabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Metric.LabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=434,
)

_METRIC = _descriptor.Descriptor(
  name='Metric',
  full_name='api.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.Metric.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='api.Metric.labels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Metric.values', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_METRIC_LABELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=634,
)


_SAMPLEPAIR = _descriptor.Descriptor(
  name='SamplePair',
  full_name='api.SamplePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='api.SamplePair.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.SamplePair.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=636,
  serialized_end=705,
)


_WRITEMETRICSREQUEST = _descriptor.Descriptor(
  name='WriteMetricsRequest',
  full_name='api.WriteMetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='api.WriteMetricsRequest.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=707,
  serialized_end=758,
)

_QUERYMETRICSREQUEST_LABELSENTRY.containing_type = _QUERYMETRICSREQUEST
_QUERYMETRICSREQUEST.fields_by_name['labels'].message_type = _QUERYMETRICSREQUEST_LABELSENTRY
_QUERYMETRICSREQUEST.fields_by_name['start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_QUERYMETRICSREQUEST.fields_by_name['end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_QUERYMETRICSREQUEST.fields_by_name['step'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_QUERYMETRICSREQUEST.fields_by_name['chunkSize'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_QUERYMETRICSRESPONSE.fields_by_name['metrics'].message_type = _METRIC
_METRIC_LABELSENTRY.containing_type = _METRIC
_METRIC.fields_by_name['labels'].message_type = _METRIC_LABELSENTRY
_METRIC.fields_by_name['values'].message_type = _SAMPLEPAIR
_SAMPLEPAIR.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WRITEMETRICSREQUEST.fields_by_name['metrics'].message_type = _METRIC
DESCRIPTOR.message_types_by_name['QueryMetricsRequest'] = _QUERYMETRICSREQUEST
DESCRIPTOR.message_types_by_name['QueryMetricsResponse'] = _QUERYMETRICSRESPONSE
DESCRIPTOR.message_types_by_name['Metric'] = _METRIC
DESCRIPTOR.message_types_by_name['SamplePair'] = _SAMPLEPAIR
DESCRIPTOR.message_types_by_name['WriteMetricsRequest'] = _WRITEMETRICSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryMetricsRequest = _reflection.GeneratedProtocolMessageType('QueryMetricsRequest', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _QUERYMETRICSREQUEST_LABELSENTRY,
    '__module__' : 'api.metrics_pb2'
    # @@protoc_insertion_point(class_scope:api.QueryMetricsRequest.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : _QUERYMETRICSREQUEST,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.QueryMetricsRequest)
  })
_sym_db.RegisterMessage(QueryMetricsRequest)
_sym_db.RegisterMessage(QueryMetricsRequest.LabelsEntry)

QueryMetricsResponse = _reflection.GeneratedProtocolMessageType('QueryMetricsResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYMETRICSRESPONSE,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.QueryMetricsResponse)
  })
_sym_db.RegisterMessage(QueryMetricsResponse)

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _METRIC_LABELSENTRY,
    '__module__' : 'api.metrics_pb2'
    # @@protoc_insertion_point(class_scope:api.Metric.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : _METRIC,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.Metric)
  })
_sym_db.RegisterMessage(Metric)
_sym_db.RegisterMessage(Metric.LabelsEntry)

SamplePair = _reflection.GeneratedProtocolMessageType('SamplePair', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEPAIR,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.SamplePair)
  })
_sym_db.RegisterMessage(SamplePair)

WriteMetricsRequest = _reflection.GeneratedProtocolMessageType('WriteMetricsRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEMETRICSREQUEST,
  '__module__' : 'api.metrics_pb2'
  # @@protoc_insertion_point(class_scope:api.WriteMetricsRequest)
  })
_sym_db.RegisterMessage(WriteMetricsRequest)


_QUERYMETRICSREQUEST_LABELSENTRY._options = None
_METRIC_LABELSENTRY._options = None

_METRICS = _descriptor.ServiceDescriptor(
  name='Metrics',
  full_name='api.Metrics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=761,
  serialized_end=891,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='api.Metrics.Query',
    index=0,
    containing_service=None,
    input_type=_QUERYMETRICSREQUEST,
    output_type=_QUERYMETRICSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='api.Metrics.Write',
    index=1,
    containing_service=None,
    input_type=_WRITEMETRICSREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METRICS)

DESCRIPTOR.services_by_name['Metrics'] = _METRICS

# @@protoc_insertion_point(module_scope)
