// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/metrics.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryMetricsRequest struct {
	MetricName           string               `protobuf:"bytes,1,opt,name=metricName,proto3" json:"metricName,omitempty"`
	Labels               map[string]string    `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	ChunkSize            *duration.Duration   `protobuf:"bytes,5,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryMetricsRequest) Reset()         { *m = QueryMetricsRequest{} }
func (m *QueryMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMetricsRequest) ProtoMessage()    {}
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82f4d3bdff1c5591, []int{0}
}

func (m *QueryMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMetricsRequest.Unmarshal(m, b)
}
func (m *QueryMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMetricsRequest.Marshal(b, m, deterministic)
}
func (m *QueryMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMetricsRequest.Merge(m, src)
}
func (m *QueryMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryMetricsRequest.Size(m)
}
func (m *QueryMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMetricsRequest proto.InternalMessageInfo

func (m *QueryMetricsRequest) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *QueryMetricsRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *QueryMetricsRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *QueryMetricsRequest) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *QueryMetricsRequest) GetChunkSize() *duration.Duration {
	if m != nil {
		return m.ChunkSize
	}
	return nil
}

type QueryMetricsResponse struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryMetricsResponse) Reset()         { *m = QueryMetricsResponse{} }
func (m *QueryMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMetricsResponse) ProtoMessage()    {}
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82f4d3bdff1c5591, []int{1}
}

func (m *QueryMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMetricsResponse.Unmarshal(m, b)
}
func (m *QueryMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMetricsResponse.Marshal(b, m, deterministic)
}
func (m *QueryMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMetricsResponse.Merge(m, src)
}
func (m *QueryMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryMetricsResponse.Size(m)
}
func (m *QueryMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMetricsResponse proto.InternalMessageInfo

func (m *QueryMetricsResponse) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metric struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Values               []*SamplePair     `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_82f4d3bdff1c5591, []int{2}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Metric) GetValues() []*SamplePair {
	if m != nil {
		return m.Values
	}
	return nil
}

type SamplePair struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value                float64              `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SamplePair) Reset()         { *m = SamplePair{} }
func (m *SamplePair) String() string { return proto.CompactTextString(m) }
func (*SamplePair) ProtoMessage()    {}
func (*SamplePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_82f4d3bdff1c5591, []int{3}
}

func (m *SamplePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SamplePair.Unmarshal(m, b)
}
func (m *SamplePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SamplePair.Marshal(b, m, deterministic)
}
func (m *SamplePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SamplePair.Merge(m, src)
}
func (m *SamplePair) XXX_Size() int {
	return xxx_messageInfo_SamplePair.Size(m)
}
func (m *SamplePair) XXX_DiscardUnknown() {
	xxx_messageInfo_SamplePair.DiscardUnknown(m)
}

var xxx_messageInfo_SamplePair proto.InternalMessageInfo

func (m *SamplePair) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *SamplePair) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type WriteMetricsRequest struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WriteMetricsRequest) Reset()         { *m = WriteMetricsRequest{} }
func (m *WriteMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*WriteMetricsRequest) ProtoMessage()    {}
func (*WriteMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82f4d3bdff1c5591, []int{4}
}

func (m *WriteMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteMetricsRequest.Unmarshal(m, b)
}
func (m *WriteMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteMetricsRequest.Marshal(b, m, deterministic)
}
func (m *WriteMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteMetricsRequest.Merge(m, src)
}
func (m *WriteMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_WriteMetricsRequest.Size(m)
}
func (m *WriteMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteMetricsRequest proto.InternalMessageInfo

func (m *WriteMetricsRequest) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryMetricsRequest)(nil), "api.QueryMetricsRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.QueryMetricsRequest.LabelsEntry")
	proto.RegisterType((*QueryMetricsResponse)(nil), "api.QueryMetricsResponse")
	proto.RegisterType((*Metric)(nil), "api.Metric")
	proto.RegisterMapType((map[string]string)(nil), "api.Metric.LabelsEntry")
	proto.RegisterType((*SamplePair)(nil), "api.SamplePair")
	proto.RegisterType((*WriteMetricsRequest)(nil), "api.WriteMetricsRequest")
}

func init() { proto.RegisterFile("api/metrics.proto", fileDescriptor_82f4d3bdff1c5591) }

var fileDescriptor_82f4d3bdff1c5591 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x95, 0xb3, 0xf9, 0x50, 0x26, 0x07, 0xc0, 0xad, 0xc0, 0x5d, 0xa4, 0x12, 0x45, 0x20, 0x72,
	0x72, 0xa4, 0x80, 0x44, 0x8b, 0xc2, 0x8d, 0xde, 0x00, 0x81, 0x5b, 0x89, 0xb3, 0xd3, 0x0e, 0xc5,
	0xea, 0x7e, 0x18, 0xdb, 0x8b, 0x14, 0x8e, 0xfc, 0x23, 0x7e, 0x0d, 0x7f, 0x07, 0x65, 0xec, 0x28,
	0x69, 0x12, 0x3e, 0x24, 0x6e, 0xf6, 0xcc, 0x7b, 0xb3, 0xcf, 0xef, 0xcd, 0xc2, 0x3d, 0x6d, 0xcd,
	0xa4, 0xc4, 0xe0, 0xcc, 0xa5, 0x97, 0xd6, 0xd5, 0xa1, 0xe6, 0x99, 0xb6, 0x26, 0x7f, 0x78, 0x5d,
	0xd7, 0xd7, 0x05, 0x4e, 0xa8, 0x34, 0x6f, 0x3e, 0x4d, 0xb0, 0xb4, 0x61, 0x11, 0x11, 0xf9, 0xa3,
	0xed, 0x66, 0x30, 0x25, 0xfa, 0xa0, 0x4b, 0x9b, 0x00, 0xc7, 0xdb, 0x80, 0xab, 0xc6, 0xe9, 0x60,
	0xea, 0x2a, 0xf6, 0x47, 0x3f, 0x5b, 0x70, 0xf0, 0xa1, 0x41, 0xb7, 0x78, 0x1b, 0xbf, 0xac, 0xf0,
	0x4b, 0x83, 0x3e, 0xf0, 0x63, 0x80, 0xa8, 0xe5, 0x9d, 0x2e, 0x51, 0xb0, 0x21, 0x1b, 0xf7, 0xd5,
	0x46, 0x85, 0xcf, 0xa0, 0x5b, 0xe8, 0x39, 0x16, 0x5e, 0xb4, 0x86, 0xd9, 0x78, 0x30, 0x7d, 0x2c,
	0xb5, 0x35, 0x72, 0xcf, 0x24, 0xf9, 0x86, 0x60, 0x67, 0x55, 0x70, 0x0b, 0x95, 0x38, 0xfc, 0x04,
	0xfa, 0x3e, 0x68, 0x17, 0x2e, 0x4c, 0x89, 0x22, 0x1b, 0xb2, 0xf1, 0x60, 0x9a, 0xcb, 0xa8, 0x54,
	0xae, 0x94, 0xca, 0x8b, 0xd5, 0x53, 0xd4, 0x1a, 0xcc, 0x9f, 0x43, 0x0f, 0xab, 0x2b, 0xe2, 0xb5,
	0xff, 0xca, 0x5b, 0x41, 0xf9, 0x0b, 0xe8, 0x5f, 0x7e, 0x6e, 0xaa, 0x9b, 0x73, 0xf3, 0x0d, 0x45,
	0x87, 0x78, 0x47, 0x3b, 0xbc, 0xd7, 0xc9, 0x19, 0xb5, 0xc6, 0xe6, 0xa7, 0x30, 0xd8, 0xd0, 0xcf,
	0xef, 0x42, 0x76, 0x83, 0x8b, 0x64, 0xc7, 0xf2, 0xc8, 0x0f, 0xa1, 0xf3, 0x55, 0x17, 0x0d, 0x8a,
	0x16, 0xd5, 0xe2, 0xe5, 0x65, 0xeb, 0x84, 0x8d, 0x5e, 0xc1, 0xe1, 0x6d, 0x3b, 0xbc, 0xad, 0x2b,
	0x8f, 0xfc, 0x09, 0xf4, 0x52, 0xca, 0x82, 0x91, 0x75, 0x03, 0xb2, 0x2e, 0xc2, 0xd4, 0xaa, 0x37,
	0xfa, 0xc1, 0xa0, 0x1b, 0x6b, 0x9c, 0x43, 0xbb, 0x5a, 0xa7, 0x40, 0x67, 0x3e, 0xd9, 0xf2, 0xff,
	0xc1, 0xc6, 0x90, 0xbd, 0x96, 0x3f, 0x85, 0x2e, 0x69, 0xf3, 0x22, 0x23, 0xc2, 0x1d, 0x22, 0x9c,
	0xeb, 0xd2, 0x16, 0xf8, 0x5e, 0x1b, 0xa7, 0x52, 0xfb, 0x7f, 0x9e, 0xac, 0x00, 0xd6, 0x03, 0xb9,
	0x84, 0xf6, 0x72, 0x1b, 0x89, 0xfa, 0xe7, 0x9c, 0x08, 0x77, 0x7b, 0x2e, 0x4b, 0x73, 0x47, 0x33,
	0x38, 0xf8, 0xe8, 0x4c, 0xc0, 0xad, 0xfd, 0xfc, 0x37, 0x17, 0xa7, 0xdf, 0x19, 0xf4, 0x12, 0x93,
	0xcf, 0xa0, 0x43, 0x81, 0x70, 0xf1, 0xbb, 0x5d, 0xcd, 0x8f, 0xf6, 0x74, 0x52, 0x6c, 0xa7, 0xd0,
	0x21, 0x1d, 0x89, 0xbd, 0x47, 0x53, 0x7e, 0x7f, 0xe7, 0x89, 0x67, 0xcb, 0x5f, 0x75, 0xde, 0xa5,
	0xfb, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xc3, 0xad, 0xc2, 0xe2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricsClient interface {
	Query(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error)
	Write(ctx context.Context, in *WriteMetricsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type metricsClient struct {
	cc *grpc.ClientConn
}

func NewMetricsClient(cc *grpc.ClientConn) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) Query(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error) {
	out := new(QueryMetricsResponse)
	err := c.cc.Invoke(ctx, "/api.Metrics/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) Write(ctx context.Context, in *WriteMetricsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.Metrics/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
type MetricsServer interface {
	Query(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	Write(context.Context, *WriteMetricsRequest) (*empty.Empty, error)
}

// UnimplementedMetricsServer can be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (*UnimplementedMetricsServer) Query(ctx context.Context, req *QueryMetricsRequest) (*QueryMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedMetricsServer) Write(ctx context.Context, req *WriteMetricsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}

func RegisterMetricsServer(s *grpc.Server, srv MetricsServer) {
	s.RegisterService(&_Metrics_serviceDesc, srv)
}

func _Metrics_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Metrics/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Query(ctx, req.(*QueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Metrics/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Write(ctx, req.(*WriteMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Metrics_Query_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Metrics_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/metrics.proto",
}
